### ISSUE TITLE
Question regarding the alignment scores

### ISSUE THREAD

**Issue by yangxiaofeng** [THU-LYJ-Lab/T3Bench#1]
If I get an average alignment score 3, 
then the normalized score is 3/5x100 = 60
or (3-1)/4x100 = 50 ?
Currently based on your paper sec 4.2, I assume the second calculation is correct. 
Is that right?

**Comment by hyz317** [comment]
Yes, the second is correct.

**Comment by yangxiaofeng** [comment]
Thanks for your response!
