### ISSUE TITLE
Question regarding text prompts

### ISSUE THREAD

**Issue by AndreAmaduzzi** [THU-LYJ-Lab/T3Bench#3]
Hello! Thanks for your interesting work. I have a question regarding the text prompts you release in this benchmark.
I am wondering if you are providing triplets of the increasingly descriptive text prompts for every object. or if every text prompt is referring to a random object. 

For example: 
- **single object** : "A red fire hydrant"
- **single object with surroundings**: "A red fire hydrant on a sidewalk"
- **multiple objects**: "A red fire hydrant is on a sidewalk close to a large tree".

**Comment by hyz317** [comment]
Hi there,

Thank you for your interest in our work! To clarify, the text prompts in our benchmark are generated randomly and are not specifically tailored to follow a pattern of increasingly descriptive triplets for each object.

**Comment by AndreAmaduzzi** [comment]
OK, very clear.

Thanks,
Andrea
