### ISSUE TITLE
Generation time

### ISSUE THREAD

**Issue by taoranyi** [THU-LYJ-Lab/T3Bench#4]
Hello, this is a wonderful job. I would like to know the generation time of these methods (ProlificDreamer, SJC, Fantasia3D, LatentNeRF, Magic3D, Dreamfusion) in the paper?

**Comment by hyz317** [comment]
Sorry for the late reply and thank you for your interest in our work!

Regarding the generation times of the methods mentioned in the paper, here is the breakdown (per prompt on a single A100 GPU):

DreamFusion: ~ 30min
Magic3D: ~ 40min (two stages)
LatentNeRF: ~ 65min (two stages)
Fantasia3D: ~ 45min (two stages)
SJC: ~ 25min
ProlificDreamer: ~ 4h
