### ISSUE TITLE
Release request for mesh results of the newly added methods

### ISSUE THREAD

**Issue by victor-thu** [THU-LYJ-Lab/T3Bench#7]
Wonderful work! I've been following this work for a while and I noticed that in your latest submission for ECCV 24, several recent work like MVDream, DreamGaussian, etc. are added in the leaderboard. I'm wondering that whether the mesh results of these newly added methods can be released like the last update in 2023/10/24. I'm planning to leverage these mesh results as part of my dataset. I'll be very appreciated for their release. Overall, T3Bench is truly a contributing work and wish your submission for ECCV be accepted ASAP.
Thanks again! And look forward to your reply.

**Comment by hyz317** [comment]
Hi,

Thank you for your kind words and for following our work on our work!
I apologize for the delay in making these results available; there were some server issues that I've now resolved.
The mesh results are now available for download:

https://drive.google.com/file/d/1TjnIvT8WVt8_1qmLKSxUDz64irrm5siA/view?usp=sharing

Please let me know if you have any trouble accessing them.

**Comment by hyz317** [comment]
Hi,

Thank you for your kind words and following our work!
I apologize for the delay in making these results available; there were some server issues that I've now resolved.
The mesh results are now available for download:

https://drive.google.com/file/d/1TjnIvT8WVt8_1qmLKSxUDz64irrm5siA/view?usp=sharing

Please let me know if you have any trouble accessing them.

**Comment by victor-thu** [comment]
Thanks for your generous release! It will be of great help. I have obtained those mesh results through the link you provide successfully and there doesn't seem to be any trouble at the moment. Thanks again!
